@baseUrl = http://localhost:8000/api


############################################
### 1. 全ユーザ取得
############################################
GET {{baseUrl}}/users/
Accept: application/json


############################################
### 2. ユーザ新規作成
############################################
POST {{baseUrl}}/users/
Content-Type: application/json
Accept: application/json

{
  "name": "shiori"
}

###
@userId = 4
############################################
### 3. 特定ユーザ取得
############################################
GET {{baseUrl}}/users/{{userId}}/
Accept: application/json


############################################
### 4. ユーザ部分更新（PATCH）
############################################
PATCH {{baseUrl}}/users/{{userId}}/
Content-Type: application/json
Accept: application/json

{
  "tickets_very_hard": -1,
  "tickets_hard": 0,
  "tickets_normal": 10,
  "tickets_easy": 10,
  "tickets_very_easy": 10
}


############################################
### 5. ユーザ削除
############################################
DELETE {{baseUrl}}/users/{{userId}}/
Accept: application/json
