# Generated by Django 6.0 on 2025-12-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ticket_gold',
            new_name='tickets_gold',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ticket_peru',
            new_name='tickets_peru',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ticket_plum',
            new_name='tickets_plum',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ticket_silver',
            new_name='tickets_silver',
        ),
    ]
