# Generated by Django 6.0 on 2025-12-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_ticket_gold_user_tickets_gold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
