# Generated by Django 6.0 on 2025-12-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_habit_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='tuseday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
