# Generated by Django 6.0 on 2026-01-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reward_difficulty_reward_is_purchased_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='tuseday',
            new_name='tuesday',
        ),
    ]
