# Generated by Django 6.0 on 2026-01-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_tuseday_habit_tuesday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tickets_gold',
            new_name='tickets_easy',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tickets_peru',
            new_name='tickets_hard',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tickets_plum',
            new_name='tickets_normal',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tickets_silver',
            new_name='tickets_very_easy',
        ),
        migrations.AddField(
            model_name='user',
            name='tickets_very_hard',
            field=models.IntegerField(default=0),
        ),
    ]
